### ISSUE TITLE
mac 0.10.3 not refreshing 

### ISSUE THREAD

**Issue by Jake-rnz** [jvolker/miq-nz-booking-tools#107]
Thank you so much for developing and updating this script, it is incredibly apprecited!

Was using previous build successfully, running mac os catalina 10.15.7

downloaded and began using new version today

navigate to secure allocation page, receive following notice, but page does not refresh automatically 

Found "Secure your allocation" page! Wait for beep sound, confirm the date selected is what you want, then do the reCAPTCHA and click 'next' to continue booking.

Thanks again!!

**Comment by Jake-rnz** [comment]
Welcome to the MIQ Booking Assistance!
A new browser window should appear. Please navigate to "Secure your allocation" page.
Found "Secure your allocation" page! Wait for beep sound, confirm the date selected is what you want, then do the reCAPTCHA and click 'next' to continue booking.
(node:1895) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'scrollIntoView' of null
    at __puppeteer_evaluation_script__:3:18
    at ExecutionContext._evaluateInternal (/Applications/miq-nz-booking-assistance.app/Contents/Resources/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/Applications/miq-nz-booking-assistance.app/Contents/Resources/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async findAvailability (/Applications/miq-nz-booking-assistance.app/Contents/Resources/app/miq-assistance.js:142:12)
    at async prepareAndCheckPage (/Applications/miq-nz-booking-assistance.app/Contents/Resources/app/miq-assistance.js:120:9)
    at async /Applications/miq-nz-booking-assistance.app/Contents/Resources/app/miq-assistance.js:90:13
(Use `miq-nz-booking-assistance --trace-warnings ...` to show where the warning was created)
(node:1895) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1895) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Jake-rnz** [comment]
Randomly started working successfully for a few hours and then stopped refreshing automatically again. 

The above was created by running the script from the package contents of the application. 

Sorry I do not possess any coding knowledge, I'm not sure if the above is relevant or has any useful information/ can provide a solution to the issue?


Thank you again for all your hard work! Much appreciated, hopefully I can get home soon! :D
